server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gymflow_erp}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_VOTRE_CLE_SECRETE_ICI}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_test}
  success-url: ${STRIPE_SUCCESS_URL:http://localhost:5173/client/payment-success}
  cancel-url: ${STRIPE_CANCEL_URL:http://localhost:5173/client/payment-cancel}
